language: cpp
cache: apt
env:
  - QT_SELECT=qt5
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt542
  - sudo apt-get update
  - sudo apt-get install qt54base qt54svg qt54tools
  - source /opt/qt54/bin/qt54-env.sh
script:
  - qmake
  - make
