cache: apt
dist: trusty
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt542-trusty
  - sudo apt-get update
  - sudo apt-get install qt54base qt54svg qt54tools
  - source /opt/qt54/bin/qt54-env.sh
language: cpp
script:
  - qmake
  - make
sudo: required
